### ISSUE TITLE
Cant get any feedback from VSCode when using extension

### ISSUE THREAD

**Issue by Soremwar** [axetroy/vscode-deno#117]
**Describe the bug**
When I open VSCode i'm welcomed by this error screen:

```log
The TypeScript language service died 5 times right after it got started. The service will not be restarted

TypeError: Cannot read property 'refCount' of undefined
    at removeDirectoryWatcher (tsserver.js:101954:13)
    at stopWatchFailedLookupLocationOfResolution (tsserver.js:101943:25)
    at tsserver.js:101749:21
    at Map.forEach (<anonymous>)
    at resolveNamesWithLocalCache (tsserver.js:101747:31)
    at Object.resolveTypeReferenceDirectives (tsserver.js:101773:20)
    at InferredProject.Project.resolveTypeReferenceDirectives (tsserver.js:139322:45)
    at /home/nicolas/.vscode/extensions/axetroy.vscode-deno-3.4.0/node_modules/typescript-deno-plugin/out/typescript-deno-plugin/src/plugin.js:110:42
    at Array.map (<anonymous>)
    at InferredProject.languageServiceHost.resolveTypeReferenceDirectives (/home/nicolas/.vscode/extensions/axetroy.vscode-deno-3.4.0/node_modules/typescript-deno-plugin/out/typescript-deno-plugin/src/plugin.js:108:22)
    at Object.compilerHost.resolveTypeReferenceDirectives (tsserver.js:135201:64)
    at resolveTypeReferenceDirectiveNamesWorker (tsserver.js:97730:137)
    at Object.createProgram (tsserver.js:97816:35)
    at synchronizeHostData (tsserver.js:135218:26)
    at Proxy.getProgram (tsserver.js:135310:13)
    at InferredProject.Project.updateGraphWorker (tsserver.js:139786:53)
    at InferredProject.Project.updateGraph (tsserver.js:139729:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (tsserver.js:141705:25)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:143132:26)
    at tsserver.js:143396:107
    at Object.mapDefined (tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Additional Notes**

I'm currently working on a Linux machine (Elementary OS ubuntu based).

**Screenshots**

![Service could not be started VSCode](https://user-images.githubusercontent.com/42647963/77988289-96b6ec80-72e1-11ea-81be-b27b6ee27a7b.png)

**Versions**

vscode: 1.43.2
deno: 0.38.0
extension: 3.4.0

**Comment by axetroy** [comment]
Actually, I fixed this bug a few days ago, But I didn't release a new version.

I will release a new version later
