### ISSUE TITLE
Extension crash if import_map.json has no "imports" key

### ISSUE THREAD

**Issue by shian15810** [axetroy/vscode-deno#132]
**Describe the bug**

Should be related to this line of code:

https://github.com/axetroy/vscode-deno/blob/v3.5.0/core/import_map.ts#L74

`Deno Language Server` error log in vscode output:

```
(node:18173) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ImportMap.[Symbol.iterator] (~/.vscode/extensions/axetroy.vscode-deno-3.5.0/server/out/core/import_map.js:60:29)
    at ImportMap.resolveModule (~/.vscode/extensions/axetroy.vscode-deno-3.5.0/server/out/core/import_map.js:46:18)
    at ModuleResolver.resolveFromLocal (~/.vscode/extensions/axetroy.vscode-deno-3.5.0/server/out/core/module_resolver.js:79:38)
    at ModuleResolver.resolveModules (~/.vscode/extensions/axetroy.vscode-deno-3.5.0/server/out/core/module_resolver.js:118:39)
    at handle (~/.vscode/extensions/axetroy.vscode-deno-3.5.0/server/out/server/src/language/diagnostics.js:104:47)
    at Diagnostics.generate (~/.vscode/extensions/axetroy.vscode-deno-3.5.0/server/out/server/src/language/diagnostics.js:125:19)
    at async Diagnostics.diagnosis (~/.vscode/extensions/axetroy.vscode-deno-3.5.0/server/out/server/src/language/diagnostics.js:136:26)
```

**To Reproduce**

`./.vscode/settings.json`:

```json
{
  "deno.enable": true,
  "deno.import_map": "./import_map.json"
}
```

`./import_map.json`:

```json
{}
```

**Expected behavior**

Should ignore `import_map.json` if it has no `imports` key instead of crashing.

**Screenshots**

![Screen Shot 2020-04-09 at 2 37 54 PM](https://user-images.githubusercontent.com/22716548/78865184-bb445e80-7a6f-11ea-8a8e-905a2cf1ae95.png)

**Versions**

vscode: 1.44.0
deno: 0.40.0
extension: 3.5.0

**Comment by axetroy** [comment]
This is very strange because I have added test cases

https://github.com/axetroy/vscode-deno/blob/508882629e66987efe0c2c1de24eccc7e494f9a1/core/import_map.test.ts#L10-L32

**Comment by axetroy** [comment]
I tried to fix this.

Please try in 3.5.1.

**Comment by shian15810** [comment]
@axetroy Tried 3.5.1, solved!

Thanks for the fast feedback and bug fixing.

Keep up the amazing work!!!
