### ISSUE TITLE
TypeScript Language Server crash when module redirect to a relative path

### ISSUE THREAD

**Issue by codehz** [axetroy/vscode-deno#97]
### crash 

**Describe the bug**

TypeScript Language Server crash when module redirect to a relative path (301, and Location: /xxx.ts)

**To Reproduce**

PS: I have host a cloudflare worker for that ( localhost server not working, that's an another issue )
```typescript
import "https://tsissues.codehz.workers.dev/relative";
```
<details>
  <summary>cloudflare worker code</summary>
<p>

```javascript
addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})

/**
 * Respond to the request
 * @param {Request} request
 */
async function handleRequest(request) {
  const url = new URL(request.url);
  switch (url.pathname) {
    case "/relative":
      return new Response(null, {
        status: 301,
        headers: {
          Location: "/target.ts"
        }
      });
    case "/absolute":
      return new Response(null, {
        status: 301,
        headers: {
          Location: `https://${url.host}/target.ts`
        }
      });
    case "/target.ts":
      return new Response("console.log(`hello, world`)", {
        headers: {
          "Content-Type": "text/typescript"
        }
      });
    default:
      return new Response("try /relative or /absolute", { status: 404 });
  }
}
```

</p>
</details>

PS: it works in deno cli

**Expected behavior**

TypeScript Language Server not crash and get type definition

**Screenshots**

![image](https://user-images.githubusercontent.com/13158903/76725869-7d169080-678a-11ea-87d3-7ac8bbe1ce42.png)

<details>
  <summary>Exception</summary>
<p>

```
TypeError [ERR_INVALID_URL]: Invalid URL: /target.ts
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at ModuleResolver.resolveFromRemote (C:\Users\CodeHz\.vscode\extensions\axetroy.vscode-deno-3.2.1\node_modules\typescript-deno-plugin\out\core\module_resolver.js:38:21)
    at ModuleResolver.resolveFromRemote (C:\Users\CodeHz\.vscode\extensions\axetroy.vscode-deno-3.2.1\node_modules\typescript-deno-plugin\out\core\module_resolver.js:48:25)
    at ModuleResolver.resolveModules (C:\Users\CodeHz\.vscode\extensions\axetroy.vscode-deno-3.2.1\node_modules\typescript-deno-plugin\out\core\module_resolver.js:100:43)
    at InferredProject.info.languageServiceHost.resolveModuleNames (C:\Users\CodeHz\.vscode\extensions\axetroy.vscode-deno-3.2.1\node_modules\typescript-deno-plugin\out\typescript-deno-plugin\src\plugin.js:198:50)
    at Object.compilerHost.resolveModuleNames (tsserver.js:135192:52)
    at resolveModuleNamesWorker (tsserver.js:97713:127)
    at resolveModuleNamesReusingOldState (tsserver.js:97983:24)
    at processImportedModules (tsserver.js:99448:35)
    at findSourceFile (tsserver.js:99191:17)
    at tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (tsserver.js:98987:34)
    at processSourceFile (tsserver.js:99020:13)
    at processRootFile (tsserver.js:98843:13)
    at tsserver.js:97809:60
    at Object.forEach (tsserver.js:167:30)
    at Object.createProgram (tsserver.js:97809:16)
    at synchronizeHostData (tsserver.js:135218:26)
    at Proxy.getProgram (tsserver.js:135310:13)
    at InferredProject.Project.updateGraphWorker (tsserver.js:139786:53)
    at InferredProject.Project.updateGraph (tsserver.js:139729:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (tsserver.js:141705:25)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:143132:26)
    at tsserver.js:143396:107
    at Object.mapDefined (tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```
</p>

</details>

**Versions**

vscode:
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
vscode: 1.43.0
typescript: 3.8.3
deno: 0.36.0
extension: 3.2.1

**Comment by axetroy** [comment]
confirmed. It will be fixed soon.

**Comment by axetroy** [comment]
v3.3.0 has been released and has fixed this issue.

If it still exists, welcome to reopen the issue
